### ISSUE TITLE
Hide Personas section when no filters are selected

### ISSUE THREAD

**Issue by srhboo** [law-design-colab-ctto/family-law-costs#17]
Current:
<img width="1606" alt="screen shot 2018-08-14 at 2 13 51 pm" src="https://user-images.githubusercontent.com/5035757/44109951-60fbf214-9fcc-11e8-8bb2-342662e02a67.png">
- The personas section is seen even when there are no filters selected (and no personas displayed)

Expected:
- Hide Personas section when no filters are selected
- When there are at least one filter(s) selected but no personas to list/display, there should be a message for the user "Looks like there are no personas that match! Try adjusting the stage, job stability, and ability to handle stress."

**Comment by averyau** [comment]
Hi Sarah and Eric, 

I thought we had wanted all the personas to appear in the persona section when no filters are selected  - in other words, filter acts to remove personas from the list, narrowing down options for users. 

For second bullet under Expected, we could have something like: 

"Looks like there are no personas that match! Try adjusting / clearing the filters for stage, job stability, or ability to handle stress."

Please let me know your thoughts - thanks!
