### ISSUE TITLE
As a user, I should be able to see how the incurred direct costs measure up with a persona's income at the end of a section

### ISSUE THREAD

**Issue by srhboo** [law-design-colab-ctto/family-law-costs#34]
<img width="830" alt="screen shot 2018-08-25 at 8 49 53 pm" src="https://user-images.githubusercontent.com/5035757/44623851-85f1f980-a8a8-11e8-9ae0-b9382b4e2d33.png">

- Outlined box
- $$ value display
- Horizontal bar graph comparing costs (so far) and income

**Comment by re-mint** [comment]
I created the component, and put it at the end of the persona pages. Where should it really be?

**Comment by averyau** [comment]
Hi Eric, check out the Figma file page called "Avery Proof" for where we'd like the bar chart to go- we're thinking of having two bar charts: 
1. at end of Total Costs of the Case section 
2. at end of life Total Life Costs section

**Comment by srhboo** [comment]
merged
