### ISSUE TITLE
As a user I should be able to access a page to read about the tool

### ISSUE THREAD

**Issue by srhboo** [law-design-colab-ctto/family-law-costs#45]
<img width="670" alt="screen shot 2018-09-19 at 5 33 34 pm" src="https://user-images.githubusercontent.com/5035757/45782901-4792f480-bc32-11e8-893b-3a924a74789f.png">

- Should be found at /about
- Should contain all text seen in design
- Standard footer and header

**Comment by averyau** [comment]
I am getting content for this page from Sarah and Meredith
