### ISSUE TITLE
As a user, I should be able to see the persona's eligibility for legal aid after selecting representation

### ISSUE THREAD

**Issue by srhboo** [law-design-colab-ctto/family-law-costs#46]
<img width="505" alt="screen shot 2018-09-19 at 5 37 30 pm" src="https://user-images.githubusercontent.com/5035757/45783090-d142c200-bc32-11e8-971d-edcfedff1e25.png">
<img width="555" alt="screen shot 2018-09-19 at 5 37 36 pm" src="https://user-images.githubusercontent.com/5035757/45783099-d43db280-bc32-11e8-91c0-dd019a24132e.png">

- Update `selectReasonsForLegalAidEligibility` in `persona-page.selectors` to return the correct notifications according to the above logic
- Text should use correct pronouns according to persona

**Comment by nkxy** [comment]
https://github.com/law-design-colab-ctto/family-law-costs/pull/62

**Comment by averyau** [comment]
**Note** 

A notification only appears if a user chooses "Lawyer" 

If a user chooses "Self", then no notification should appear
