### ISSUE TITLE
As a user I should be able to see a persona card on the persona page

### ISSUE THREAD

**Issue by srhboo** [law-design-colab-ctto/family-law-costs#47]
<img width="521" alt="screen shot 2018-09-19 at 5 40 17 pm" src="https://user-images.githubusercontent.com/5035757/45783219-2b438780-bc33-11e8-8f02-c4c0d5fbb1fc.png">

- Update styling of the persona card found on persona page
- Include image corresponding to persona

**Comment by re-mint** [comment]
Clarification here on Chip 3 labeled 'Children'? What's the images corresponding to the personas?

**Comment by srhboo** [comment]
on this
