### ISSUE TITLE
As a user I should be able to see a calculated childcare cost on the persona page

### ISSUE THREAD

**Issue by srhboo** [law-design-colab-ctto/family-law-costs#50]
<img width="392" alt="screen shot 2018-09-19 at 6 03 54 pm" src="https://user-images.githubusercontent.com/5035757/45784358-64312b80-bc36-11e8-9113-ec40326a55e7.png">

- Update `addChildcareFees` in `persona-page.selectors` to correctly calculate childcare fees (use OOP data and calculations spreadsheet)

**Comment by averyau** [comment]
**Calculate Childcare costs**

If Number of Children > 0
Total Days Missed * Childcare cost per day (given province) * Number of Children

If Number of Children = 0 
Childcare costs = 0 and hide this section entirely
