### ISSUE TITLE
As a user I should be able to see the calculate moving costs on the persona page

### ISSUE THREAD

**Issue by srhboo** [law-design-colab-ctto/family-law-costs#51]
<img width="426" alt="screen shot 2018-09-19 at 6 08 49 pm" src="https://user-images.githubusercontent.com/5035757/45784545-1668f300-bc37-11e8-91a4-3d542031a597.png">
- Update `addMovingFees` in `persona-page.selectors` to correctly calculate moving fees (use OOP data and calculations spreadsheet)

**Comment by averyau** [comment]
**Calculate Moving Costs**

If moving = y, 
Moving costs = moving costs given province

If moving = n, 
Moving costs = 0 and hide this section entirely
